swagger: '2.0'
info:
  description: |-
    Микросервис для отправки сообщения "Пора пить чай" пользователям в 17:00 по Московскому времени в рабочие дни
  version: 2.0.0
  title: message-sender
basePath: /message_sender/v2/rest
schemes:
  - http
  - https
paths:
  /list:
    get:
      tags:
      - user
      summary: Получение списка всех пользователей в табличном виде
      description: "Возвращает список всех пользователей в табличном виде, содержащей данные: ID,Name,Email"
      operationId: restlist
      produces:
      - application/json
      responses:
        '200':
          description: "successful operation"
          schema: 
            $ref: "#/definitions/getUsersResponse"
        '500':
          description: "Критичные ошибки"
        
  /add:
    post:
      tags:
      - user
      summary: Добавление нового пользователя в базу данных
      description: "Записывает в базу данных нового пользователя с данными: ID,Name,Email"
      operationId: restadd
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Входной объект пользователя
        required: true
        schema:
          $ref: "definitions/User"

      responses:
        '200':
          description: "successful operation"
        '422':
          description: "Отправлены некорректные данные"
        '500':
          description: "Критичные ошибки"
  /delete:
    delete:
      tags:
      - user
      summary: Удаление пользователя из базы данных
      description: "Удаление информации о пользователе из базы данных"
      operationId: restdelete
      parameters:
      - name: "identifier"
        in: "query"
        type: integer
      responses:
        '200':
          description: "successful operation"
        '400':
          description: "Пользователь не найден"
        '500':
          description: "Критичные ошибки"      
definitions:
  getUsersResponse:
    type: object
    additionalProperties: false
    properties:
      users:
        type: array
        items:
          $ref: "#/definitions/User"
  User:
    type: object
    additionalProperties: false
    properties:
      id:
        description: идентификатор пользователя
        type: integer
      name:
        description: имя пользователя
        type: string
      email:
        description: email пользователя
        type: string
